### ISSUE TITLE
generation of salts

### ISSUE THREAD

**Issue by alexeinz** [lewazo/boreale#2]
Hi, thanks for this... I am not sure how to generate the required salts / keys
do you have an example for this ?

Thank you

**Comment by lewazo** [comment]
Hey sorry for the long wait, for some reason I didn't get any notification for this issue.

Personally I just use my password manager (LastPass) to generate me some random keys. You could also use online generators like https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx and use the 512 bits option. This will generate a 512 bits (or 64 bytes). This is perfect for use as the `SECRET_KEY_BASE` key. You can set the others to the same or generate new ones too.
