### ISSUE TITLE
Add support for ARM Docker image

### ISSUE THREAD

**Issue by quentinb69** [lewazo/boreale#22]
Since selfhosted is one of the target of boreal, maybe an ARM Docker image would permit better visibility and help people secure their installation without depending on external google/github/... ; non-sso basic auth ; other "big" authelia or keycloak.

**Comment by lewazo** [comment]
I think this is a great suggestion and definitely something I'll be looking to provide soon.

**Comment by lewazo** [comment]
Hi,

Starting with v1.3.1, the official docker image includes an ARM build. It is now available on the docker hub.
