### ISSUE TITLE
Username case insensitive

### ISSUE THREAD

**Issue by intelwolf** [lewazo/boreale#23]
As an improvement it would be nice to have the username case insensitive.

**Comment by lewazo** [comment]
Great suggestion, I'll fix this later in the week.
Thanks!

**Comment by lewazo** [comment]
v1.2.2 has been released on the docker hub. It now handles case insensitive usernames.

Starting now, usernames will be saved lowercased, so I suggest you remove old usernames containing uppercase letters from the authorized users list using the CLI.

Logins will work with any combination of upper/lower case.
